// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydbfuilqiyehzvkyobwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkYmZ1aWxxaXllaHp2a3lvYndoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAzMjg1NDAsImV4cCI6MjA1NTkwNDU0MH0.CNYVcmWdv0-FwV1fnPaxmoymUsiesFbOv4HwoLzr3FQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);